### ISSUE TITLE
Unhandled Promise rejection: (SystemJS) Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by stschaefer** [angular-buch/schnellstart#1]
Hi guys,

I'm trying to run the "schnellstart" example but I'm getting the error above. Any ideas?

Greetings,
Stefan

**Comment by JohannesHoppe** [comment]
Confirmed. I will anyway update everything for ng5 soon!

**Comment by GregOnNet** [comment]
I recognized a similar issue with Firefox.
If the plugin µBlock is enabled I get the following error:

```
Unhandled Promise rejection: "NetworkError when attempting to fetch resource.
  Instantiating https://unpkg.com/rxjs/operators/refCount.js
  Loading https://unpkg.com/rxjs/operators/share.js
  Loading ./app/main" ; Zone: <root> ; Task: Promise.then ; Value: Error: NetworkError when attempting to fetch resource.
  Instantiating https://unpkg.com/rxjs/operators/refCount.js
  Loading https://unpkg.com/rxjs/operators/share.js
  Loading ./app/main
```

Disabling the plugin solves that issue.

**Comment by JohannesHoppe** [comment]
They even injected a warning now:
![image](https://user-images.githubusercontent.com/640639/32839127-acdd8d30-ca13-11e7-9ab9-d3a6a651784e.png)

**Comment by JohannesHoppe** [comment]
So we added a warning now:
![image](https://user-images.githubusercontent.com/640639/32839470-d928bd32-ca14-11e7-9be2-736a27ac87ef.png)
