### ISSUE TITLE
404 bei rxjs-compat

### ISSUE THREAD

**Issue by JohannesHoppe** [angular-buch/schnellstart#3]
von @moerker, siehe https://github.com/angular-buch/schnellstart/commit/0a9dd8d6d12207191764e2fb84ee36ad01160e4e#commitcomment-28751855

> Leider kein "app works" mit einem clone des Projektes, es bleibt beim "loading...". Die Komponente wird nicht geloaden, stattdessen gibt es ein 404 für "rxjs-..." in der Lite-Server Ausgabe.
>
>[Browsersync] Serving files from: ./
>[Browsersync] Watching files...
>18.04.26 13:37:50 304 GET /index.html
>18.04.26 13:37:50 304 GET /systemjs.config.js
>18.04.26 13:37:51 304 GET /app/main.ts
>18.04.26 13:37:51 304 GET /favicon.ico
>18.04.26 13:37:52 304 GET /app/app.module.ts
>18.04.26 13:37:52 304 GET /app/app.component.ts
>18.04.26 13:37:53 404 GET /rxjs-compat/Observable
>18.04.26 13:37:53 404 GET /rxjs-compat/observable/merge
>18.04.26 13:37:53 404 GET /rxjs-compat/operator/share
>18.04.26 13:37:53 404 GET /rxjs-compat/Subject

**Comment by JohannesHoppe** [comment]
Hallo @moerker, vielen Dank für den Hinweis!

Generell:
Wir überlegen gerade, in der nächsten Auflage gar nicht mehr die CDN-Lösung mit SystemJS zu erwähnen. Eher StackBlitz. Momentan hat der Schnellstart keine hohe Prio, da die Angular-CLI sowieso die bessere Lösung ist. Bei RxJS hat sich ebenso einiges geändert mittlerweile. 


Prinzipiell sollte 

A) ein weiteres mapping das ganze schon richten, siehe hier
https://github.com/angular-buch/schnellstart/blob/0a9dd8d6d12207191764e2fb84ee36ad01160e4e/systemjs.config.js#L25

oder

B) eine explizit angegebene ALTE Version von RxJS ebenso das Problem lösen.

Wenn du Zeit hast, das zu Testen, so freuen wir uns auf deinen Pull Request! Egal ob A oder B. 👍

**Comment by cn4hub** [comment]
Hallo,

Folgendes
`'rxjs': 'npm:rxjs,`
bringt nicht das gewünschte Ergebnis. 

Nach Angabe einer älteren Version funktioniert das Ganze:
`'rxjs': 'npm:rxjs@5.4.3',`

Evtl. hilft es.

**Comment by JohannesHoppe** [comment]
Genau, vielen Dank für den Hinweis! 👍 
Ich habe gar nicht expliziet erwähnt, dass ich das Problem jetzt per Versionsnummer gelöst habe: https://github.com/angular-buch/schnellstart/commit/b21bd5ec751202af9f87b1beac6b4d9adb794eae
